class BaseTargetStackGenerator:
    """
    Base class for all pluggable framework-specific target stack generators.
    """
    def __init__(self, api_key: str = None, model_name: str = "gemini-2.5-flash"):
        self.api_key = api_key
        self.model_name = model_name

    def generate_sdk(self, api_metadata: dict, use_case: str) -> str:
        """
        Generate framework-aware SDK wrapper class.
        """
        raise NotImplementedError

    def generate_rest(self, api_metadata: dict, use_case: str) -> str:
        """
        Generate framework-aware REST integration code.
        """
        raise NotImplementedError

    def generate_frontend(self, blueprint: dict) -> dict:
        """
        Generate framework-aware frontend files (filepath -> content string).
        """
        raise NotImplementedError

    def get_folder_structure(self) -> dict:
        """
        Return the recommended folder structure.
        """
        raise NotImplementedError

    def get_framework_features(self) -> list:
        """
        Return list of framework-specific features.
        """
        raise NotImplementedError

    def get_generated_assets(self) -> list:
        """
        Return a list of asset filenames generated by this stack.
        """
        raise NotImplementedError
